/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DDD;

import com.thoughtworks.ddd_workshop.DDD;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        DDD classUnderTest = new DDD();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
